"""Shared SI parameters for the Harris-sheet generator and field-line movie."""

import numpy as np


# Physical constants (SI)
KB = 1.380649e-23
MU0 = 1.25663706e-6
EPS0 = 8.85418782e-12
ELECTRON_MASS = 9.1093837e-31
ELEMENTARY_CHARGE = 1.602e-19
LIGHT_SPEED = 2.99792458e8

# Harris-sheet plasma and numerical parameters. Keep synchronized with harris_current.toml.
SEED = 20260906
SHEET_DENSITY = 1.0e22
BACKGROUND_DENSITY = 0.3 * SHEET_DENSITY
THERMAL_SPEED = 0.05 * LIGHT_SPEED
PLASMA_FREQUENCY = ELEMENTARY_CHARGE * np.sqrt(
    SHEET_DENSITY / (ELECTRON_MASS * EPS0)
)
SKIN_DEPTH = LIGHT_SPEED / PLASMA_FREQUENCY
# Per-species Debye length at the sheet reference density.
DEBYE_LENGTH = THERMAL_SPEED / PLASMA_FREQUENCY
SHEET_HALF_WIDTH = 0.5 * SKIN_DEPTH
LX = 15.0 * SKIN_DEPTH
LY = DEBYE_LENGTH
LZ = 15.0 * SKIN_DEPTH
NX = 300
NY = 1
NZ = 300

# The two species each supply n_0 k_B T to the sheet pressure.
TEMPERATURE = ELECTRON_MASS * THERMAL_SPEED**2 / KB
B0 = np.sqrt(
    4.0 * MU0 * SHEET_DENSITY * ELECTRON_MASS * THERMAL_SPEED**2
)
DRIFT_SPEED = B0 / (
    2.0
    * MU0
    * ELEMENTARY_CHARGE
    * SHEET_DENSITY
    * SHEET_HALF_WIDTH
)
PERTURBATION_FRACTION = 0.05

N_SHEET_PARTICLES = 100_000
N_BACKGROUND_PARTICLES = 450_000
N_PARTICLES_PER_SPECIES = N_SHEET_PARTICLES + N_BACKGROUND_PARTICLES
SHEET_COLUMN_DENSITY = (
    2.0
    * SHEET_DENSITY
    * SHEET_HALF_WIDTH
    * np.tanh(LZ / (2.0 * SHEET_HALF_WIDTH))
)
MACROPARTICLE_WEIGHT = SHEET_COLUMN_DENSITY * LX * LY / N_SHEET_PARTICLES


CYCLOTRON_FREQUENCY = ELEMENTARY_CHARGE * B0 / ELECTRON_MASS
