# This workflow will install Python dependencies, and run tests with a single version of Python 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Testing

on:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    env:
      JAX_PLATFORMS: cpu
      JAX_ENABLE_X64: "1"
      JAX_NUM_CPU_DEVICES: "1"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      id: install
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Code tests
      run: python -m unittest discover -s tests/code_tests -t . -p '*test*.py'
    - name: Physics tests
      if: ${{ !cancelled() && steps.install.outcome == 'success' }}
      run: python -m unittest discover -s tests/physics_tests -t . -p '*test*.py'
    - name: Distributed tests
      if: ${{ !cancelled() && steps.install.outcome == 'success' }}
      env:
        JAX_NUM_CPU_DEVICES: "8"
      run: python -m unittest discover -s tests/distributed_tests -t . -p '*test*.py'
